### ISSUE TITLE
拓扑分析：做相应的实验，了解各种操作或定义的使用方法

### ISSUE THREAD

**Issue by JJwangbilin** [Orientsoft/search-front#20]

**Comment by pixcai** [comment]
定义：
{
    defailedNode: {                         // 系统名字，在`modes`里定义，
        volume: {
            default: {        　                // 顶层节点相关配置
                top: {                              // 圆环里面上面一行文字的配置
                    header: 'RPS',            // 文字
                    format: '0.0%',           // 数据格式
                    data: 'data.volume'    // 数据，只能是数字，取值有'data.volume'、'data.classPercents'、'data.globalClassPercents', 分别表示当前节点的子节点总数、当前节点的错误百分比、当前节点和所有子节点一起的平均错误百分比
                },
                bottom: {}                      // 圆环里面下面一行文字的配置，同上
            },
            entry: {},                             // 顶层入口节点配置，同上
            region: {}                 　　    // 子节点配置，同上
        }
    }
}

**Comment by pixcai** [comment]
connections配置信息含义：
```
{
    source: 'INTERNET',        // 源节点名字
    target: 'proxy-prod',        // 目标节点名字
    class: 'warning',               // 连接状态，'normal'、'warning'或'danger'
    metrics: {                          // 连接所包含的数据信息
        aa: 10,                           // 表明aa类型的数据有10条，每次随机发出10个小圆点
        bb: 2                             // 表明bb类型的数据有2条，每次随机发出2个小圆点
    },
    notices: [{                         // 在连接上显示的额外内容
        title: 'hello',                   // 要显示的文字
        severity: 0                     // 状态，0表示普通信息，1表示警告信息，2表示错误信息
    }]
}
```

**Comment by pixcai** [comment]
node配置信息含义:
```
{
    name: 'core',    // 节点名字
    displayName: '核心',    // 用于显示在图上的名字，不填默认为`name`的值
    renderer: 'global',    // 顶层节点还是子节点，`global`代表顶层节点，`region`代表子节点
    class: 'normal',    // 节点状态
    nodes: [],    // 包含的子节点
    connections: []    // 子节点的连接信息
}
```
